# **********************
# *** Subdirectories ***
# **********************

#subdir('decrunch')

# ********************
# *** Source Files ***
# ********************

rasm_sources = files(
	'rasm.c'
)

# *****************
# *** All Files ***
# *****************

#rasm_all_files = rasm_headers + RASM.process(rasm_decrunch_sources)

# ***************
# *** Library ***
# ***************

#librasm = static_library(
#	'apultra',
#	rasm_all_files
#)